name: Build-OpenWrt
on:
  push:
    branches:
      - master

jobs:
  rm2100:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment
      run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get update
          sudo apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf ecj fastjar mkisofs
          sudo apt-get -qq autoremove --purge
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

    - name: Source code
      run: |
          git clone https://github.com/coolsnowwolf/lede
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          curl -L https://raw.githubusercontent.com/Retayihtevr/My-OpenWrt-Action/master/rm2100/.config >> .config
          make defconfig
          bash -c "$(curl -L https://raw.githubusercontent.com/Retayihtevr/My-OpenWrt-Action/master/rm2100/set_config.sh)"

    - name: Download dl library
      run: |
          pwd
          cd lede
          make -j8 download

    - name: Runing Compile
      run: |
          pwd
          cd lede
          make -j2 V=99

    - name: Only Upload firmware (Without packages)
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: mt7621
        path: lede/bin/targets/*/*
        